[workspace]
members = ["crates/app", "crates/config", "crates/scheduler", "crates/utils"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.104"
arc-swap = "1.9.2"
chrono = "0.4.45"
dumpsys-rs = { git = "https://github.com/reigadegr/dumpsys-rs" }
inotify = { version = "0.11.5", default-features = false }
mimalloc = { version = "0.1.52", features = ["override", "v2", "no_thp"] }
rustix = { version = "1.1.4", features = ["fs", "mount"] }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
taplo = { version = "0.14.0", default-features = false }
toml = { version = "1.1.5", default-features = false, features = [
  "parse",
  "serde",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
expect_used = { level = "warn", priority = -1 }
similar_names = "allow"
missing_errors_doc = "allow"
missing_safety_doc = "allow"
missing_panics_doc = "allow"
cast_precision_loss = "allow"
cast_possible_truncation = "allow"
struct_excessive_bools = "allow"
option_if_let_else = "allow"

[profile.dev]
debug = true
debug-assertions = true
panic = "abort"
incremental = true

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "thin"
opt-level = 2
strip = true
debug = 0
debug-assertions = false
incremental = false
panic = "abort"
